version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DB_PASSWORD=laravel
      - MARIADB_USER=laravel
      - MARIADB_DATABASE=laravel    
    volumes:
      - './DB_BACKUP:/DB_BACKUP'
  app:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=laravel
      - DB_DATABASE=laravel
    volumes:
      - './:/app'
    depends_on:
      - mariadb
